### ISSUE TITLE
bug: ERR_OSSL_EVP_UNSUPPORTED on Node 17.2.0

### ISSUE THREAD

**Issue by alercah** [ffxiv-teamcraft/ffxiv-teamcraft#2105]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**

**To Reproduce**
Follow the installation instructions in `CONTRIBUTING.md`, with Node.js 17.2.0, and run `yarn start`.

**Expected behavior**
The server starts.

**Log**
```
yarn run v1.22.17
warning ../../package.json: No license field
$ yarn prebuild && yarn ng-high-memory serve --project=client
warning ../../package.json: No license field
$ node ./tools/build/prebuild.js && yarn update-lazy-files && yarn web:copyfiles

Running pre-build tasks
warning ../../package.json: No license field
$ node ./tools/build/lazy-files-updater.js
Updating lazy loaded files list
Lazy loaded files list updated
Updating lazy loaded data Models
Lazy loaded data Models updated
Updating lazy loaded data interface
Lazy loaded data interface updated
warning ../../package.json: No license field
$ copyfiles ./libs/loader/tc-loader.js ./apps/client/src/assets/ -f
warning ../../package.json: No license field
$ node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng serve --project=client
Node.js version v17.2.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
⠋ Generating browser application bundles (phase: setup)...Warning: Entry point '@kaiu/ng-serializer' contains deep imports into '/home/alercah/code/ffxiv-teamcraft/node_modules/@kaiu/serializer/index'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
⠹ Generating browser application bundles (phase: building)...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/alercah/code/ffxiv-teamcraft/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/alercah/code/ffxiv-teamcraft/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/home/alercah/code/ffxiv-teamcraft/node_modules/@angular-devkit/build-angular/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:231:8)
    at NormalModule._initBuildHash (/home/alercah/code/ffxiv-teamcraft/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/home/alercah/code/ffxiv-teamcraft/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModule.js:946:10)
    at /home/alercah/code/ffxiv-teamcraft/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModule.js:1040:4
    at processResult (/home/alercah/code/ffxiv-teamcraft/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModule.js:755:11)
    at /home/alercah/code/ffxiv-teamcraft/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModule.js:819:5
    at /home/alercah/code/ffxiv-teamcraft/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/home/alercah/code/ffxiv-teamcraft/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at iterateNormalLoaders (/home/alercah/code/ffxiv-teamcraft/node_modules/loader-runner/lib/LoaderRunner.js:239:10)
    at /home/alercah/code/ffxiv-teamcraft/node_modules/loader-runner/lib/LoaderRunner.js:254:3
    at context.callback (/home/alercah/code/ffxiv-teamcraft/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/alercah/code/ffxiv-teamcraft/node_modules/@angular-devkit/build-angular/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
error Command failed with exit code 1
```

**Desktop (please complete the following information):**
 - OS: Debian stable
 - Browser: N/A
 - Version: HEAD

**Comment by Supamiu** [comment]
I'm closing this as related to Angular itself, not Teamcraft.

Node 17 is unsupported for now, and it'll be until Angular itself supports it.

Node 16 is working fine, tho.
