### ISSUE TITLE
bug: After gathering when a list is open the list will become unresponsive.

### ISSUE THREAD

**Issue by Blackcatz1911** [ffxiv-teamcraft/ffxiv-teamcraft#2390]
**Describe the bug**
After gathering when a list is open the list will become unresponsive.

**To Reproduce**
1. Go to 'Lists'.
2. Open a list.
3. Farm materials.
4. See error in console.
5. "Inventory" and others button wont respond anymore to clicks.

**Expected behavior**
No error and normal usage.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Desktop App
 - Version 9.9.2

**Additional context**
```
Uncaught TypeError: Cannot read properties of undefined (reading 'gathering') polyfills.95243e679e13e13a.js:1
    at jS (main.2a805d6325dda9ca.js:1:3819401)
    at main.2a805d6325dda9ca.js:1:5360878
    at main.2a805d6325dda9ca.js:1:5359365
    at main.2a805d6325dda9ca.js:1:5359821
    at Ht (main.2a805d6325dda9ca.js:1:5363693)
    at main.2a805d6325dda9ca.js:1:4417754
    at y._next (main.2a805d6325dda9ca.js:1:4405492)
    at y.value (polyfills.95243e679e13e13a.js:1:8339)
    at a.Lv.next (polyfills.95243e679e13e13a.js:1:7133)
    at main.2a805d6325dda9ca.js:1:4425029
    at y._next (main.2a805d6325dda9ca.js:1:4405492)
    at y.value (polyfills.95243e679e13e13a.js:1:8339)
    at a.Lv.next (polyfills.95243e679e13e13a.js:1:7133)
    at main.2a805d6325dda9ca.js:1:4415691
    at A.<anonymous> (main.2a805d6325dda9ca.js:1:4436703)
```

**Comment by Supamiu** [comment]
Hi, thank you for your report, I'm going to work on this asap 😄
