### ISSUE TITLE
Can't load inventory

### ISSUE THREAD

**Issue by PommeVerte** [ffxiv-teamcraft/ffxiv-teamcraft#2481]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
I can't load inventory with packet capture. I get a console error when the app runs. 

**To Reproduce**
Run the app (I'm running as admin)
Go to the inventory optimizer

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 10.1.6 of the desktop app

**Additional context**
To be on the safe side I allowed the app in the firewall. 

Here's the console error:

```
ipc.service.ts:392 NAVIGATE /inventory-optimizer
client.js:125 WebSocket connection to 'wss://gubal.hasura.app/v1/graphql' failed: WebSocket is closed before the connection is established.
W.close @ client.js:125
Show 1 more frame
client.js:125 WebSocket connection to 'wss://gubal.hasura.app/v1/graphql' failed: WebSocket is closed before the connection is established.
W.close @ client.js:125
(anonymous) @ client.js:439
Show 2 more frames
main.ts:30 fun-hooks: referenced 'adpod' but it was never created
console.warn @ main.ts:30
(anonymous) @ prebid.js.br:2
(anonymous) @ prebid.js.br:2
ready.u.ready @ prebid.js.br:2
(anonymous) @ prebid.js.br:2
K.processQueue @ prebid.js.br:2
(anonymous) @ prebid.js.br:2
(anonymous) @ prebid.js.br:2
(anonymous) @ prebid.js.br:2
main.ts:43 Error: no provided or inferred data
    at new A (zone-error.js:92:33)
    at zh (gpt.js:10:37187)
    at qh (gpt.js:10:35144)
    at gpt.js:10:37711
    at gpt.js:10:38505
console.error @ main.ts:43
Z.R @ pubads_impl_2023020101.js?cb=31072165:10
(anonymous) @ pubads_impl_2023020101.js?cb=31072165:10
Uq @ pubads_impl_2023020101.js?cb=31072165:10
Wq.throw @ pubads_impl_2023020101.js?cb=31072165:10
c @ pubads_impl_2023020101.js?cb=31072165:10
invoke @ zone.js:372
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
runTask @ zone.js:178
C @ zone.js:585
Promise.then (async)
Et @ zone.js:561
$ @ zone.js:572
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
Dt @ zone.js:1265
Tt @ zone.js:1202
(anonymous) @ zone.js:1118
(anonymous) @ zone.js:1134
$y @ pubads_impl_2023020101.js?cb=31072165:10
(anonymous) @ pubads_impl_2023020101.js?cb=31072165:10
Bh.addListener @ gpt.js:10
(anonymous) @ gpt.js:10
DI @ pubads_impl_2023020101.js?cb=31072165:10
VI @ pubads_impl_2023020101.js?cb=31072165:10
(anonymous) @ pubads_impl_2023020101.js?cb=31072165:18
(anonymous) @ pubads_impl_2023020101.js?cb=31072165:18
(anonymous) @ pubads_impl_2023020101.js?cb=31072165:18
Show 15 more frames
amp-inabox.js:129 Powered by AMP ⚡ HTML – Version 2301181928000 file:///C:/Users/admin/AppData/Local/ffxiv-teamcraft/app-10.1.6/resources/app.asar/dist/apps/client/index.html
amp-ad-exit.js:443 Unrecognized feature: 'attribution-reporting'.
detectAttributionReportingSupport @ amp-ad-exit.js:443
et @ amp-ad-exit.js:103
cs @ custom-element.js:1317
Bi @ custom-element.js:1250
upgrade @ custom-element.js:379
Ir @ custom-element-registry.js:97
br @ custom-element-registry.js:82
(anonymous) @ custom-element-registry.js:40
Sc @ extensions-impl.js:390
Vc @ extensions-impl.js:378
(anonymous) @ extensions-impl.js:340
addDocFactory @ extensions-impl.js:445
addElement @ extensions-impl.js:339
(anonymous) @ amp-ad-exit.js:586
f @ amp-ad-exit.js:586
registerExtension @ extensions-impl.js:162
(anonymous) @ runtime.js:205
Promise.then (async)
(anonymous) @ runtime.js:201
ni @ chunk.js:190
pi @ chunk.js:409
(anonymous) @ chunk.js:465
Promise.then (async)
Ei @ chunk.js:464
gi @ chunk.js:483
Pi @ chunk.js:368
runForStartup @ chunk.js:357
Zn @ chunk.js:59
(anonymous) @ runtime.js:315
h @ runtime.js:216
(anonymous) @ runtime.js:257
(anonymous) @ timer-impl.js:71
setTimeout (async)
delay @ timer-impl.js:77
(anonymous) @ runtime.js:510
Dh @ runtime.js:239
(anonymous) @ runtime.js:326
ni @ chunk.js:190
pi @ chunk.js:409
(anonymous) @ chunk.js:465
Promise.then (async)
Ei @ chunk.js:464
gi @ chunk.js:483
(anonymous) @ chunk.js:435
Promise.then (async)
pi @ chunk.js:424
(anonymous) @ chunk.js:465
Promise.then (async)
Ei @ chunk.js:464
gi @ chunk.js:483
(anonymous) @ chunk.js:435
Promise.then (async)
pi @ chunk.js:424
(anonymous) @ chunk.js:465
Promise.then (async)
Ei @ chunk.js:464
gi @ chunk.js:483
(anonymous) @ chunk.js:435
Promise.then (async)
pi @ chunk.js:424
(anonymous) @ chunk.js:465
Promise.then (async)
Ei @ chunk.js:464
gi @ chunk.js:483
Pi @ chunk.js:368
runForStartup @ chunk.js:357
Zn @ chunk.js:59
(anonymous) @ amp-inabox.js:64
(anonymous) @ version.js:11

```

**Comment by Supamiu** [comment]
Hi, please use the [Discord server](https://discord.gg/r6qxt6P) for packet capture troubleshooting, we have plenty of tutorials there and people to help you find what's wrong.
