### ISSUE TITLE
bug: custom alarm with a spawn time will result in an infinite loop and breaking display

### ISSUE THREAD

**Issue by Jengines** [ffxiv-teamcraft/ffxiv-teamcraft#2600]
**Describe the bug**
When creating a custom alarm with a spawn time (2:00 by example) it will result in a infinite loop for next weather detection and completly break the alarms page

**To Reproduce**
1. Go to 'Alarms' page
2. Click on 'Add custom alarm'
3. Fill the fileds according to provided screenshot below
4. See that no alarm will be created (but the popup will say 'Alarm created'
5. Refresh the page, the page is blank and an error is displayed in console

**Expected behavior**
A custom alarm with a defined spawn should be created and not breaking the alarms page

**Screenshots**
![image](https://user-images.githubusercontent.com/26380350/236679480-d1e0a794-171e-4e11-afba-2345d76768b6.png)

**Desktop (please complete the following information):**
 - OS: Windows (11)
 - Browser
 - Version: 10.4.10

**Additional context**
Console debug error: 

```
portUnhandledError.js:10 Uncaught RangeError: Maximum call stack size exceeded
    at O.nextWeatherTime (weather.service.ts:81:10)
    at O.getNextDiffWeatherTime (weather.service.ts:23:34)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
    at O.getNextDiffWeatherTime (weather.service.ts:27:17)
n
```

Look's like the timestamp is a bit too higher (according to added logs) 

> date Sat Jun 08 3067 02:00:00 GMT+0200 (heure d’été d’Europe centrale)
weather.service.ts:84 timestamp34631625600116

**Comment by Jengines** [comment]
Will fix this error too with an incoming pull request!

**Comment by Jengines** [comment]
The bug is caused by a next weather transition who never exist (but can be created from custom alarm form), I have added a catch on maxCallStack, let me know if this is a good approach.

See: #2602

**Comment by Supamiu** [comment]
lgtm !
