### ISSUE TITLE
crash: [ERR] [SubmarineTracker] Webhook post failed.

### ISSUE THREAD

**Issue by TeranFethril** [ffxiv-teamcraft/ffxiv-teamcraft#2706]
The game crashes after a submarine returns and the completion message is acknowledged.

**Describe the bug**
1.

2023-09-29 19:48:16.191 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wOS0yOVQxOTo0ODoxNi4xOTExMzIyKzAyOjAwIiwiSW5mbyI6IlN5c3RlbS5VbmF1dGhvcml6ZWRBY2Nlc3NFeGNlcHRpb246IEFjY2VzcyB0byB0aGUgcGF0aCBpcyBkZW5pZWQuXHJcbiAgIGF0IFN5c3RlbS5JTy5GaWxlU3lzdGVtLk1vdmVGaWxlKFN0cmluZyBzb3VyY2VGdWxsUGF0aCwgU3RyaW5nIGRlc3RGdWxsUGF0aCwgQm9vbGVhbiBvdmVyd3JpdGUpXHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuUGx1Z2luLkVudHJ5VXBsb2FkKERldGFpbGVkTG9vdCBsb290KSBpbiAvd29yay9yZXBvL1N1Ym1hcmluZVRyYWNrZXIvUGx1Z2luLmNzOmxpbmUgMzk0XHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuRGF0YS5Mb290LlN1Ym1hcmluZUxvb3QuQWRkTG9vdEVudHJ5KFVJbnQzMiByZXR1cm5UaW1lLCBTdWJtYXJpbmVCdWlsZCBidWlsZCwgU3BhbmAxIGRhdGEpIGluIC93b3JrL3JlcG8vU3VibWFyaW5lVHJhY2tlci9EYXRhL0xvb3QuY3M6bGluZSAzNVxyXG4gICBhdCBTdWJtYXJpbmVUcmFja2VyLk1hbmFnZXIuSG9va01hbmFnZXIuUGFja2V0UmVjZWl2ZXIoVUludDMyIHBhcmFtMSwgVUludDE2IHBhcmFtMiwgU0J5dGUgcGFyYW0zLCBJbnQ2NCBwYXJhbTQsIENoYXIgcGFyYW01KSBpbiAvd29yay9yZXBvL1N1Ym1hcmluZVRyYWNrZXIvTWFuYWdlci9Ib29rTWFuYWdlci5jczpsaW5lIDMyXHJcbiAgIGF0IERhbGFtdWQuR2FtZS5OZXR3b3JrLkdhbWVOZXR3b3JrLlByb2Nlc3Nab25lUGFja2V0RG93bkRldG91cihJbnRQdHIgYSwgVUludDMyIHRhcmdldElkLCBJbnRQdHIgZGF0YVB0cikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcR2FtZVxcTmV0d29ya1xcR2FtZU5ldHdvcmsuY3M6bGluZSAxMjMiLCJDb250ZXh0IjoiRXhjZXB0aW9uIG9uIFByb2Nlc3Nab25lUGFja2V0RG93biBob29rLiBIZWFkZXI6IDQ4LTAwLTAwLTAwLTAwLTAwLTAwLTAwLUUwLTYwLTZELUNELTY4LTAyLTAwLTAwLTE0LTAwLUQ5LTAwLTAwLTAwLTUyLTAwLURGLTBELTE3LTY1LTAwLTAwLTAwLTAwIn0=
2023-09-29 19:48:16.190 +02:00 [ERR] Exception on ProcessZonePacketDown hook. Header: 48-00-00-00-00-00-00-00-E0-60-6D-CD-68-02-00-00-14-00-D9-00-00-00-52-00-DF-0D-17-65-00-00-00-00
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at SubmarineTracker.Plugin.EntryUpload(DetailedLoot loot) in /work/repo/SubmarineTracker/Plugin.cs:line 394
   at SubmarineTracker.Data.Loot.SubmarineLoot.AddLootEntry(UInt32 returnTime, SubmarineBuild build, Span`1 data) in /work/repo/SubmarineTracker/Data/Loot.cs:line 35
   at SubmarineTracker.Manager.HookManager.PacketReceiver(UInt32 param1, UInt16 param2, SByte param3, Int64 param4, Char param5) in /work/repo/SubmarineTracker/Manager/HookManager.cs:line 32
   at Dalamud.Game.Network.GameNetwork.ProcessZonePacketDownDetour(IntPtr a, UInt32 targetId, IntPtr dataPtr) in C:\goatsoft\companysecrets\dalamud\Game\Network\GameNetwork.cs:line 123

--------------

2.

2023-09-28 16:49:17.275 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wOS0yOFQxNjo0OToxNy4yNzUzMjY3KzAyOjAwIiwiSW5mbyI6IlN5c3RlbS5VbmF1dGhvcml6ZWRBY2Nlc3NFeGNlcHRpb246IEFjY2VzcyB0byB0aGUgcGF0aCBpcyBkZW5pZWQuXHJcbiAgIGF0IFN5c3RlbS5JTy5GaWxlU3lzdGVtLk1vdmVGaWxlKFN0cmluZyBzb3VyY2VGdWxsUGF0aCwgU3RyaW5nIGRlc3RGdWxsUGF0aCwgQm9vbGVhbiBvdmVyd3JpdGUpXHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuUGx1Z2luLkVudHJ5VXBsb2FkKERldGFpbGVkTG9vdCBsb290KSBpbiAvd29yay9yZXBvL1N1Ym1hcmluZVRyYWNrZXIvUGx1Z2luLmNzOmxpbmUgMzk2XHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuRGF0YS5Mb290LlN1Ym1hcmluZUxvb3QuQWRkTG9vdEVudHJ5KFVJbnQzMiByZXR1cm5UaW1lLCBTdWJtYXJpbmVCdWlsZCBidWlsZCwgU3BhbmAxIGRhdGEpIGluIC93b3JrL3JlcG8vU3VibWFyaW5lVHJhY2tlci9EYXRhL0xvb3QuY3M6bGluZSAzNVxyXG4gICBhdCBTdWJtYXJpbmVUcmFja2VyLk1hbmFnZXIuSG9va01hbmFnZXIuUGFja2V0UmVjZWl2ZXIoVUludDMyIHBhcmFtMSwgVUludDE2IHBhcmFtMiwgU0J5dGUgcGFyYW0zLCBJbnQ2NCBwYXJhbTQsIENoYXIgcGFyYW01KSBpbiAvd29yay9yZXBvL1N1Ym1hcmluZVRyYWNrZXIvTWFuYWdlci9Ib29rTWFuYWdlci5jczpsaW5lIDMyXHJcbiAgIGF0IERhbGFtdWQuR2FtZS5OZXR3b3JrLkdhbWVOZXR3b3JrLlByb2Nlc3Nab25lUGFja2V0RG93bkRldG91cihJbnRQdHIgYSwgVUludDMyIHRhcmdldElkLCBJbnRQdHIgZGF0YVB0cikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcR2FtZVxcTmV0d29ya1xcR2FtZU5ldHdvcmsuY3M6bGluZSAxMjMiLCJDb250ZXh0IjoiRXhjZXB0aW9uIG9uIFByb2Nlc3Nab25lUGFja2V0RG93biBob29rLiBIZWFkZXI6IEZGLUZGLUZGLUZGLUZGLUZGLUZGLUZGLTQwLUVCLTUxLTZCLUVBLTAyLTAwLTAwLTE0LTAwLUQ5LTAwLTAwLTAwLTU0LTAxLTZCLTkyLTE1LTY1LTAwLTAwLTAwLTAwIn0=
2023-09-28 16:49:17.275 +02:00 [ERR] Exception on ProcessZonePacketDown hook. Header: FF-FF-FF-FF-FF-FF-FF-FF-40-EB-51-6B-EA-02-00-00-14-00-D9-00-00-00-54-01-6B-92-15-65-00-00-00-00
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at SubmarineTracker.Plugin.EntryUpload(DetailedLoot loot) in /work/repo/SubmarineTracker/Plugin.cs:line 396
   at SubmarineTracker.Data.Loot.SubmarineLoot.AddLootEntry(UInt32 returnTime, SubmarineBuild build, Span`1 data) in /work/repo/SubmarineTracker/Data/Loot.cs:line 35
   at SubmarineTracker.Manager.HookManager.PacketReceiver(UInt32 param1, UInt16 param2, SByte param3, Int64 param4, Char param5) in /work/repo/SubmarineTracker/Manager/HookManager.cs:line 32
   at Dalamud.Game.Network.GameNetwork.ProcessZonePacketDownDetour(IntPtr a, UInt32 targetId, IntPtr dataPtr) in C:\goatsoft\companysecrets\dalamud\Game\Network\GameNetwork.cs:line 123

--------------

3.

2023-09-28 07:39:10.390 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wOS0yOFQwNzozOToxMC4zODk1NzEzKzAyOjAwIiwiSW5mbyI6IlN5c3RlbS5VbmF1dGhvcml6ZWRBY2Nlc3NFeGNlcHRpb246IEFjY2VzcyB0byB0aGUgcGF0aCBpcyBkZW5pZWQuXHJcbiAgIGF0IFN5c3RlbS5JTy5GaWxlU3lzdGVtLk1vdmVGaWxlKFN0cmluZyBzb3VyY2VGdWxsUGF0aCwgU3RyaW5nIGRlc3RGdWxsUGF0aCwgQm9vbGVhbiBvdmVyd3JpdGUpXHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuUGx1Z2luLkVudHJ5VXBsb2FkKERldGFpbGVkTG9vdCBsb290KSBpbiAvd29yay9yZXBvL1N1Ym1hcmluZVRyYWNrZXIvUGx1Z2luLmNzOmxpbmUgMzk2XHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuRGF0YS5Mb290LlN1Ym1hcmluZUxvb3QuQWRkTG9vdEVudHJ5KFVJbnQzMiByZXR1cm5UaW1lLCBTdWJtYXJpbmVCdWlsZCBidWlsZCwgU3BhbmAxIGRhdGEpIGluIC93b3JrL3JlcG8vU3VibWFyaW5lVHJhY2tlci9EYXRhL0xvb3QuY3M6bGluZSAzNVxyXG4gICBhdCBTdWJtYXJpbmVUcmFja2VyLk1hbmFnZXIuSG9va01hbmFnZXIuUGFja2V0UmVjZWl2ZXIoVUludDMyIHBhcmFtMSwgVUludDE2IHBhcmFtMiwgU0J5dGUgcGFyYW0zLCBJbnQ2NCBwYXJhbTQsIENoYXIgcGFyYW01KSBpbiAvd29yay9yZXBvL1N1Ym1hcmluZVRyYWNrZXIvTWFuYWdlci9Ib29rTWFuYWdlci5jczpsaW5lIDMyXHJcbiAgIGF0IERhbGFtdWQuR2FtZS5OZXR3b3JrLkdhbWVOZXR3b3JrLlByb2Nlc3Nab25lUGFja2V0RG93bkRldG91cihJbnRQdHIgYSwgVUludDMyIHRhcmdldElkLCBJbnRQdHIgZGF0YVB0cikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcR2FtZVxcTmV0d29ya1xcR2FtZU5ldHdvcmsuY3M6bGluZSAxMjMiLCJDb250ZXh0IjoiRXhjZXB0aW9uIG9uIFByb2Nlc3Nab25lUGFja2V0RG93biBob29rLiBIZWFkZXI6IDcwLTA5LTA4LURDLUZGLTdGLTAwLTAwLTYwLTNGLTU4LTA1LTFBLTAyLTAwLTAwLTE0LTAwLUQ5LTAwLTAwLTAwLTRCLTAxLTdELTExLTE1LTY1LTAwLTAwLTAwLTAwIn0=
2023-09-28 07:39:10.379 +02:00 [ERR] Exception on ProcessZonePacketDown hook. Header: 70-09-08-DC-FF-7F-00-00-60-3F-58-05-1A-02-00-00-14-00-D9-00-00-00-4B-01-7D-11-15-65-00-00-00-00
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at SubmarineTracker.Plugin.EntryUpload(DetailedLoot loot) in /work/repo/SubmarineTracker/Plugin.cs:line 396
   at SubmarineTracker.Data.Loot.SubmarineLoot.AddLootEntry(UInt32 returnTime, SubmarineBuild build, Span`1 data) in /work/repo/SubmarineTracker/Data/Loot.cs:line 35
   at SubmarineTracker.Manager.HookManager.PacketReceiver(UInt32 param1, UInt16 param2, SByte param3, Int64 param4, Char param5) in /work/repo/SubmarineTracker/Manager/HookManager.cs:line 32
   at Dalamud.Game.Network.GameNetwork.ProcessZonePacketDownDetour(IntPtr a, UInt32 targetId, IntPtr dataPtr) in C:\goatsoft\companysecrets\dalamud\Game\Network\GameNetwork.cs:line 123

--------------

4.

2023-09-27 15:54:54.733 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wOS0yN1QxNTo1NDo1NC43MzMxOTY5KzAyOjAwIiwiSW5mbyI6IlN5c3RlbS5VbmF1dGhvcml6ZWRBY2Nlc3NFeGNlcHRpb246IEFjY2VzcyB0byB0aGUgcGF0aCBpcyBkZW5pZWQuXHJcbiAgIGF0IFN5c3RlbS5JTy5GaWxlU3lzdGVtLk1vdmVGaWxlKFN0cmluZyBzb3VyY2VGdWxsUGF0aCwgU3RyaW5nIGRlc3RGdWxsUGF0aCwgQm9vbGVhbiBvdmVyd3JpdGUpXHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuUGx1Z2luLkVudHJ5VXBsb2FkKERldGFpbGVkTG9vdCBsb290KSBpbiAvd29yay9yZXBvL1N1Ym1hcmluZVRyYWNrZXIvUGx1Z2luLmNzOmxpbmUgMzgzXHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuRGF0YS5Mb290LlN1Ym1hcmluZUxvb3QuTG9vdEFkZChVSW50MzIgcmV0dXJuVGltZSwgU3BhbmAxIGRhdGEpIGluIC93b3JrL3JlcG8vU3VibWFyaW5lVHJhY2tlci9EYXRhL0xvb3QuY3M6bGluZSA0OVxyXG4gICBhdCBTdWJtYXJpbmVUcmFja2VyLkRhdGEuU3VibWFyaW5lcy5GY1N1Ym1hcmluZXMuQWRkU3ViTG9vdChVSW50MzIga2V5LCBVSW50MzIgcmV0dXJuVGltZSwgU3BhbmAxIGRhdGEpIGluIC93b3JrL3JlcG8vU3VibWFyaW5lVHJhY2tlci9EYXRhL1N1Ym1hcmluZS5jczpsaW5lIDk1XHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuUGx1Z2luLkZyYW1ld29ya1VwZGF0ZShGcmFtZXdvcmsgXykgaW4gL3dvcmsvcmVwby9TdWJtYXJpbmVUcmFja2VyL1BsdWdpbi5jczpsaW5lIDI4OFxyXG4gICBhdCBEYWxhbXVkLlV0aWxpdHkuRXZlbnRIYW5kbGVyRXh0ZW5zaW9ucy5IYW5kbGVJbnZva2UoQWN0aW9uIGFjdCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcVXRpbGl0eVxcRXZlbnRIYW5kbGVyRXh0ZW5zaW9ucy5jczpsaW5lIDk2IiwiQ29udGV4dCI6IkV4Y2VwdGlvbiBkdXJpbmcgcmFpc2Ugb2YgXCJWb2lkIDxJbnZva2VTYWZlbHk+Yl9fMCgpXCIifQ==
2023-09-27 15:54:54.722 +02:00 [ERR] Exception during raise of Void <InvokeSafely>b__0()
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at SubmarineTracker.Plugin.EntryUpload(DetailedLoot loot) in /work/repo/SubmarineTracker/Plugin.cs:line 383
   at SubmarineTracker.Data.Loot.SubmarineLoot.LootAdd(UInt32 returnTime, Span`1 data) in /work/repo/SubmarineTracker/Data/Loot.cs:line 49
   at SubmarineTracker.Data.Submarines.FcSubmarines.AddSubLoot(UInt32 key, UInt32 returnTime, Span`1 data) in /work/repo/SubmarineTracker/Data/Submarine.cs:line 95
   at SubmarineTracker.Plugin.FrameworkUpdate(Framework _) in /work/repo/SubmarineTracker/Plugin.cs:line 288
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96

--------------

5.

2023-09-27 09:36:48.600 +02:00 [ERR] [SubmarineTracker] Webhook post failed.
2023-09-27 09:36:48.600 +02:00 [ERR] [SubmarineTracker] An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
2023-09-27 09:36:48.619 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wOS0yN1QwOTozNjo0OC42MTkyOTkyKzAyOjAwIiwiSW5mbyI6IlN5c3RlbS5VbmF1dGhvcml6ZWRBY2Nlc3NFeGNlcHRpb246IEFjY2VzcyB0byB0aGUgcGF0aCBpcyBkZW5pZWQuXHJcbiAgIGF0IFN5c3RlbS5JTy5GaWxlU3lzdGVtLk1vdmVGaWxlKFN0cmluZyBzb3VyY2VGdWxsUGF0aCwgU3RyaW5nIGRlc3RGdWxsUGF0aCwgQm9vbGVhbiBvdmVyd3JpdGUpXHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuUGx1Z2luLkVudHJ5VXBsb2FkKERldGFpbGVkTG9vdCBsb290KSBpbiAvd29yay9yZXBvL1N1Ym1hcmluZVRyYWNrZXIvUGx1Z2luLmNzOmxpbmUgMzgzXHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuRGF0YS5Mb290LlN1Ym1hcmluZUxvb3QuTG9vdEFkZChVSW50MzIgcmV0dXJuVGltZSwgU3BhbmAxIGRhdGEpIGluIC93b3JrL3JlcG8vU3VibWFyaW5lVHJhY2tlci9EYXRhL0xvb3QuY3M6bGluZSA0OVxyXG4gICBhdCBTdWJtYXJpbmVUcmFja2VyLkRhdGEuU3VibWFyaW5lcy5GY1N1Ym1hcmluZXMuQWRkU3ViTG9vdChVSW50MzIga2V5LCBVSW50MzIgcmV0dXJuVGltZSwgU3BhbmAxIGRhdGEpIGluIC93b3JrL3JlcG8vU3VibWFyaW5lVHJhY2tlci9EYXRhL1N1Ym1hcmluZS5jczpsaW5lIDk1XHJcbiAgIGF0IFN1Ym1hcmluZVRyYWNrZXIuUGx1Z2luLkZyYW1ld29ya1VwZGF0ZShGcmFtZXdvcmsgXykgaW4gL3dvcmsvcmVwby9TdWJtYXJpbmVUcmFja2VyL1BsdWdpbi5jczpsaW5lIDI4OFxyXG4gICBhdCBEYWxhbXVkLlV0aWxpdHkuRXZlbnRIYW5kbGVyRXh0ZW5zaW9ucy5IYW5kbGVJbnZva2UoQWN0aW9uIGFjdCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcVXRpbGl0eVxcRXZlbnRIYW5kbGVyRXh0ZW5zaW9ucy5jczpsaW5lIDk2IiwiQ29udGV4dCI6IkV4Y2VwdGlvbiBkdXJpbmcgcmFpc2Ugb2YgXCJWb2lkIDxJbnZva2VTYWZlbHk+Yl9fMCgpXCIifQ==
2023-09-27 09:36:48.605 +02:00 [ERR] Exception during raise of Void <InvokeSafely>b__0()
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at SubmarineTracker.Plugin.EntryUpload(DetailedLoot loot) in /work/repo/SubmarineTracker/Plugin.cs:line 383
   at SubmarineTracker.Data.Loot.SubmarineLoot.LootAdd(UInt32 returnTime, Span`1 data) in /work/repo/SubmarineTracker/Data/Loot.cs:line 49
   at SubmarineTracker.Data.Submarines.FcSubmarines.AddSubLoot(UInt32 key, UInt32 returnTime, Span`1 data) in /work/repo/SubmarineTracker/Data/Submarine.cs:line 95
   at SubmarineTracker.Plugin.FrameworkUpdate(Framework _) in /work/repo/SubmarineTracker/Plugin.cs:line 288

--------------

**To Reproduce**
1. Go to workshop
2. Click on Planning desk
4. Manage submersibles
5. Click on <name> submarine
6. see completion message
7. press ok -> CRASH

**Expected behavior**
no crash :)

**Screenshots**
no screenshot, no error message :( only error log from AppData\Roaming\XIVLauncher\dalamud.old.log

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.8.0.0

**Additional context**
submarine is level 3?

**Comment by Supamiu** [comment]
Hi, this is the wrong repo to report that. I don't know which tool you're using, I assume a dalamud plugin because it's C# but this is definitely not Teamcraft.

Also the error is pretty clear:

```
2023-09-27 09:36:48.600 +02:00 [ERR] [SubmarineTracker] Webhook post failed.
2023-09-27 09:36:48.600 +02:00 [ERR] [SubmarineTracker] An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
```

**Comment by TeranFethril** [comment]
ohh  yes, sorry.
